### ISSUE TITLE
【Web】付款頁面調整

### ISSUE THREAD

**Issue by law580580** [yutin1987/lawapp#27]
一、服務時段更改：
1. 9:00AM起
    5:00PM止
2. 5:00PM起
    11:00PM止
3. 11:00PM起
     9:00AM止

![img_1350](https://cloud.githubusercontent.com/assets/10081800/8542861/51b12cfe-24cb-11e5-93c5-4f2a4c65f552.jpg)
![default](https://cloud.githubusercontent.com/assets/10081800/8542862/51e33aaa-24cb-11e5-92b0-7e1c71b936fd.jpg)

**Comment by yutin1987** [comment]
completed
