### ISSUE TITLE
【Web】律師頁面調整

### ISSUE THREAD

**Issue by law580580** [yutin1987/lawapp#30]
一、圖片縮小
二、律師姓名放大、後面增加律師兩字
三、底下加上律師證書字號
四、增加標語：請稍候，律師將立即與您連絡！
五、移除律師手機號碼
六、撥號圖案旋轉

![img_1351](https://cloud.githubusercontent.com/assets/10081800/8543133/4cf83372-24cd-11e5-977b-2bc77572e6c2.jpg)
![default](https://cloud.githubusercontent.com/assets/10081800/8543134/4cfc51fa-24cd-11e5-8c1a-cb8330b4597f.jpg)

**Comment by yutin1987** [comment]
completed
三、底下加上律師證書字號 (+$400)
四、增加標語：請稍候，律師將立即與您連絡！ (+$400)
五、移除律師手機號碼 (+$400)
