### ISSUE TITLE
登入好麻煩

### ISSUE THREAD

**Issue by law580580** [yutin1987/lawapp#5]
進入app後，還要跳出這幾個頁面、輸入代碼，不能直接帳密登入？
![img_0896](https://cloud.githubusercontent.com/assets/10081800/6817076/e5d4ca36-d2d6-11e4-95af-b14c4547ad05.jpg)
![img_0897](https://cloud.githubusercontent.com/assets/10081800/6817077/e5d4e91c-d2d6-11e4-878b-a208a595e5dd.jpg)

**Comment by yutin1987** [comment]
因為APP還沒上架，這是測試環境。
正常只會有最後一頁登入頁
