### ISSUE TITLE
接案頁面資訊不夠 + 多筆訂單近來時，頁面怎麼顯示？

### ISSUE THREAD

**Issue by law580580** [yutin1987/lawapp#7]
接案頁面至少要有以下資訊：
(1)客戶姓名(現在應該有，屈中恆?，但是版面要調整一下，然後骷顱頭是?)
(2)警察局的位置(像網頁那樣，有個圖示，目前只有一張地圖)
(3)警察局地址
(4)案件發出時間
(5)案件類型

希望是一欄一欄往下的資訊顯示，最底下才是我要接單。

目前這樣資訊不夠。
![img_0898](https://cloud.githubusercontent.com/assets/10081800/6817157/25e7feb2-d2d8-11e4-88e1-69fc8f44468c.jpg)

**Comment by yutin1987** [comment]
這裡是顯示清單的地方，不宜過多的資訊
(1)客戶姓名 (v)
(2)警察局的位置 (會上圖示)
(3)警察局地址 (x)
(4)案件發出時間 (x)
(5)案件類型 (用圖示表示，估摟頭是暫時)

**Comment by yutin1987** [comment]
已解決
