### ISSUE TITLE
確認接單頁面

### ISSUE THREAD

**Issue by law580580** [yutin1987/lawapp#8]
1. 預計到達時間可以系統計算嗎?(比方說google律師位置到警局的時間+10分鐘)
2. 確認接單頁面要大一點(幾乎整個螢幕)，頁面裡面可以放步驟圖，告訴律師下一步該怎麼作
   ![img_0899](https://cloud.githubusercontent.com/assets/10081800/6817220/e8269d26-d2d8-11e4-95b1-d3400b695c55.jpg)

**Comment by yutin1987** [comment]
已解決
